/**
 * Represents the complete canonical state machine for an AcquisitionPipeline.
 *
 * Source of Truth: State Machine Documentation & Mongoose Schema Design.
 * Reconciled hierarchy:
 * REQUESTED -> ACCEPTED -> CONSULTATION_SCHEDULED -> CONSULTATION_COMPLETED
 *   -> OFFER_SENT -> OFFER_ACCEPTED -> PAYMENT_COMPLETED -> CONVERTED
 *
 * Terminal states: REJECTED, WITHDRAWN, OFFER_DECLINED, CLOSED
 */
export enum AcquisitionPipelineStatus {
  REQUESTED = 'REQUESTED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
  CANCELLED = 'CANCELLED',
  CONSULTATION_SCHEDULED = 'CONSULTATION_SCHEDULED',
  CONSULTATION_COMPLETED = 'CONSULTATION_COMPLETED',
  OFFER_SENT = 'OFFER_SENT',
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  OFFER_DECLINED = 'OFFER_DECLINED',
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
  CONVERTED = 'CONVERTED',
  CLOSED = 'CLOSED',
}
