export enum Permission {
  CLIENT_PROFILE = 'CLIENT_PROFILE',
  TRAINER_PROFILE = 'TRAINER_PROFILE',
  TRAINER_AVAILABILITY = 'TRAINER_AVAILABILITY',
  TRAINER_CERTIFICATIONS = 'TRAINER_CERTIFICATIONS',
  TRAINER_SHOWCASE = 'TRAINER_SHOWCASE',
  CLIENT_DASHBOARD = 'CLIENT_DASHBOARD',
  TRAINER_DASHBOARD = 'TRAINER_DASHBOARD',
}

export const PERMISSION_ROLES: Record<Permission, string[]> = {
  [Permission.CLIENT_PROFILE]: ['CLIENT'],
  [Permission.CLIENT_DASHBOARD]: ['CLIENT'],
  [Permission.TRAINER_PROFILE]: ['TRAINER'],
  [Permission.TRAINER_AVAILABILITY]: ['TRAINER'],
  [Permission.TRAINER_CERTIFICATIONS]: ['TRAINER'],
  [Permission.TRAINER_SHOWCASE]: ['TRAINER'],
  [Permission.TRAINER_DASHBOARD]: ['TRAINER'],
};
