import { SidebarConfig } from '../types/navigation.types';

export const clientSidebarConfig: SidebarConfig = {
  portalName: 'client',
  sections: [
    {
      id: 'main',
      title: 'MAIN',
      items: [
        {
          id: 'dashboard',
          label: 'Dashboard',
          description: 'Main overview & active coaching stats',
          href: '/client',
          iconName: 'dashboard',
          status: 'active',
          pageTitle: 'Client Dashboard',
          breadcrumb: ['Dashboard', 'Overview'],
        },
        {
          id: 'find-trainers',
          label: 'Find Trainers',
          description: 'Browse, compare & hire certified coaches',
          href: '/trainers',
          iconName: 'search',
          status: 'active',
          pageTitle: 'Discover Trainers',
          breadcrumb: ['Dashboard', 'Marketplace', 'Find Trainers'],
        },
        {
          id: 'trainer-requests',
          label: 'Trainer Requests',
          description: 'Track pending and accepted coaching proposals',
          href: '/client/requests',
          iconName: 'requests',
          status: 'active',
          badge: {
            type: 'COUNT',
            count: 2,
          },
          pageTitle: 'Trainer Requests',
          breadcrumb: ['Dashboard', 'Requests'],
        },
        {
          id: 'consultations',
          label: 'Consultations',
          description: 'Upcoming 1-on-1 video intake sessions',
          href: '/client/consultations',
          iconName: 'consultations',
          status: 'active',
          pageTitle: 'Consultations',
          breadcrumb: ['Dashboard', 'Consultations'],
        },
        {
          id: 'offers',
          label: 'Offers',
          description: 'Exclusive trainer discount promotions',
          href: '/client/offers',
          iconName: 'offers',
          status: 'comingSoon',
          badge: {
            type: 'COMING_SOON',
            text: 'COMING SOON',
          },
        },
      ],
    },
    {
      id: 'my-coaching',
      title: 'MY COACHING',
      items: [
        {
          id: 'workout-programs',
          label: 'Workout Programs',
          description: 'Assigned sets, reps & exercise video guides',
          href: '/client/workouts',
          iconName: 'workouts',
          status: 'comingSoon',
          badge: {
            type: 'COMING_SOON',
            text: 'COMING SOON',
          },
        },
        {
          id: 'nutrition-plans',
          label: 'Nutrition Plans',
          description: 'Custom macro splits & weekly diet guidance',
          href: '/client/nutrition',
          iconName: 'nutrition',
          status: 'comingSoon',
          badge: {
            type: 'COMING_SOON',
            text: 'COMING SOON',
          },
        },
        {
          id: 'progress-tracking',
          label: 'Progress Tracking',
          description: 'Weight trends & strength 1RM PR curves',
          href: '/client/progress',
          iconName: 'progress',
          status: 'comingSoon',
          badge: {
            type: 'COMING_SOON',
            text: 'COMING SOON',
          },
        },
        {
          id: 'progress-photos',
          label: 'Progress Photos',
          description: 'Front, side & back physical comparison logs',
          href: '/client/photos',
          iconName: 'photos',
          status: 'comingSoon',
          badge: {
            type: 'COMING_SOON',
            text: 'COMING SOON',
          },
        },
        {
          id: 'body-measurements',
          label: 'Body Measurements',
          description: 'Chest, waist, hips & arm circumferences',
          href: '/client/measurements',
          iconName: 'measurements',
          status: 'comingSoon',
          badge: {
            type: 'COMING_SOON',
            text: 'COMING SOON',
          },
        },
        {
          id: 'goals',
          label: 'Goals',
          description: 'Target target timelines & milestone achievements',
          href: '/client/goals',
          iconName: 'goals',
          status: 'comingSoon',
          badge: {
            type: 'COMING_SOON',
            text: 'COMING SOON',
          },
        },
      ],
    },
    {
      id: 'communication',
      title: 'COMMUNICATION',
      items: [
        {
          id: 'messages',
          label: 'Messages',
          description: 'Encrypted coach chat & set video attachments',
          href: '/client/messages',
          iconName: 'messages',
          status: 'comingSoon',
          badge: {
            type: 'COMING_SOON',
            text: 'COMING SOON',
          },
        },
        {
          id: 'video-sessions',
          label: 'Video Sessions',
          description: 'Live 1-on-1 coaching video calls',
          href: '/client/video-sessions',
          iconName: 'video',
          status: 'comingSoon',
          badge: {
            type: 'COMING_SOON',
            text: 'COMING SOON',
          },
        },
        {
          id: 'notifications',
          label: 'Notifications',
          description: 'Alerts, workout reminders & coach notes',
          href: '/client/notifications',
          iconName: 'notifications',
          status: 'comingSoon',
          badge: {
            type: 'COMING_SOON',
            text: 'COMING SOON',
          },
        },
      ],
    },
    {
      id: 'payments',
      title: 'PAYMENTS',
      items: [
        {
          id: 'subscription',
          label: 'Subscription',
          description: 'Active client membership plan & billing cycle',
          href: '/client/subscription',
          iconName: 'subscription',
          status: 'comingSoon',
          badge: {
            type: 'COMING_SOON',
            text: 'COMING SOON',
          },
        },
        {
          id: 'payment-history',
          label: 'Payment History',
          description: 'Past charges & transaction receipts',
          href: '/client/payment-history',
          iconName: 'history',
          status: 'comingSoon',
          badge: {
            type: 'COMING_SOON',
            text: 'COMING SOON',
          },
        },
        {
          id: 'invoices',
          label: 'Invoices',
          description: 'Downloadable PDF invoices',
          href: '/client/invoices',
          iconName: 'invoices',
          status: 'comingSoon',
          badge: {
            type: 'COMING_SOON',
            text: 'COMING SOON',
          },
        },
      ],
    },
    {
      id: 'account',
      title: 'ACCOUNT',
      items: [
        {
          id: 'my-profile',
          label: 'My Profile',
          description: 'Personal details, fitness level & bio',
          href: '/profile/client',
          iconName: 'profile',
          status: 'active',
          pageTitle: 'My Client Profile',
          breadcrumb: ['Dashboard', 'Account', 'Profile'],
        },
        {
          id: 'settings',
          label: 'Settings',
          description: 'Security, password & notification preferences',
          href: '/client/settings',
          iconName: 'settings',
          status: 'comingSoon',
          badge: {
            type: 'COMING_SOON',
            text: 'COMING SOON',
          },
        },
        {
          id: 'help-center',
          label: 'Help Center',
          description: 'Support guides, FAQ & platform assistance',
          href: '/client/help',
          iconName: 'help',
          status: 'active',
          pageTitle: 'Help & Support',
          breadcrumb: ['Dashboard', 'Account', 'Help Center'],
        },
      ],
    },
  ],
};
