import { SidebarConfig } from '../types/navigation.types';

export const clientSidebarConfig: SidebarConfig = {
  portalName: 'client',
  sections: [
    {
      id: 'main',
      title: 'MAIN',
      items: [
        {
          id: 'dashboard',
          label: 'Dashboard',
          description: 'Main overview & active coaching stats',
          href: '/client',
          iconName: 'dashboard',
          status: 'active',
          pageTitle: 'Client Dashboard',
          breadcrumb: ['Dashboard', 'Overview'],
        },
        {
          id: 'find-trainer',
          label: 'Find Trainer',
          description: 'Discover coaches and manage acquisition journey',
          href: '/client/find-trainer',
          iconName: 'search',
          status: 'active',
          pageTitle: 'Find Trainer',
          breadcrumb: ['Dashboard', 'Find Trainer'],
          children: [
            {
              id: 'find-my-trainer',
              label: 'Find My Trainer',
              description: 'Active coach acquisition journey workspace',
              href: '/client/find-trainer',
              iconName: 'search',
              status: 'active',
              pageTitle: 'Find My Trainer',
              breadcrumb: ['Dashboard', 'Find Trainer', 'Find My Trainer'],
            },
            {
              id: 'find-trainer-history',
              label: 'History',
              description: 'Previous requests, consultations & offers',
              href: '/client/find-trainer/history',
              iconName: 'history',
              status: 'active',
              pageTitle: 'Acquisition History',
              breadcrumb: ['Dashboard', 'Find Trainer', 'History'],
            },
          ],
        },
      ],
    },
    {
      id: 'my-coaching',
      title: 'MY COACHING',
      items: [
        {
          id: 'workout-programs',
          label: 'Workout Programs',
          description: 'Assigned sets, reps & exercise video guides',
          href: '/client/workouts',
          iconName: 'workouts',
          status: 'active',
          pageTitle: 'Workout Programs',
          breadcrumb: ['Dashboard', 'My Coaching', 'Workouts'],
        },
        {
          id: 'nutrition-plans',
          label: 'Nutrition Plans',
          description: 'Custom macro splits & weekly diet guidance',
          href: '/client/nutrition',
          iconName: 'nutrition',
          status: 'active',
          pageTitle: 'Nutrition Plans',
          breadcrumb: ['Dashboard', 'My Coaching', 'Nutrition'],
        },
        {
          id: 'progress-tracking',
          label: 'Progress Tracking',
          description: 'Weight trends & strength metrics',
          href: '/client/progress',
          iconName: 'progress',
          status: 'active',
          pageTitle: 'Progress Tracking',
          breadcrumb: ['Dashboard', 'My Coaching', 'Progress'],
        },
      ],
    },
    {
      id: 'account',
      title: 'ACCOUNT',
      items: [
        {
          id: 'my-profile',
          label: 'My Profile',
          description: 'Personal details, fitness level & bio',
          href: '/profile/client',
          iconName: 'profile',
          status: 'active',
          pageTitle: 'My Client Profile',
          breadcrumb: ['Dashboard', 'Account', 'Profile'],
        },
        {
          id: 'payments',
          label: 'Payments & Billing',
          description: 'Payment history, invoices & escrow protection',
          href: '/client/payments',
          iconName: 'invoices',
          status: 'active',
          pageTitle: 'Payment & Billing',
          breadcrumb: ['Dashboard', 'Account', 'Payments'],
        },
        {
          id: 'settings',
          label: 'Settings',
          description: 'Security, password & notification preferences',
          href: '/client/settings',
          iconName: 'settings',
          status: 'active',
          pageTitle: 'Settings',
          breadcrumb: ['Dashboard', 'Account', 'Settings'],
        },
        {
          id: 'help-center',
          label: 'Help Center',
          description: 'Support guides, FAQ & platform assistance',
          href: '/client/help',
          iconName: 'help',
          status: 'active',
          pageTitle: 'Help & Support',
          breadcrumb: ['Dashboard', 'Account', 'Help Center'],
        },
      ],
    },
  ],
};
