import { SidebarConfig } from '../types/navigation.types';

export const trainerSidebarConfig: SidebarConfig = {
  portalName: 'trainer',
  sections: [
    {
      id: 'main',
      title: 'MAIN',
      items: [
        {
          id: 'trainer-dashboard',
          label: 'Dashboard',
          description: 'Overview of coaching activity & client management',
          href: '/trainer',
          iconName: 'dashboard',
          status: 'active',
          pageTitle: 'Overview',
          breadcrumb: ['Dashboard', 'Overview'],
        },
      ],
    },
    {
      id: 'coaching',
      title: 'COACHING',
      items: [
        {
          id: 'trainer-requests',
          label: 'Requests',
          description: 'Pending client intake & coaching proposals',
          href: '/trainer/requests',
          iconName: 'requests',
          status: 'active',
          pageTitle: 'Client Requests',
          breadcrumb: ['Dashboard', 'Requests'],
        },
        {
          id: 'trainer-consultations',
          label: 'Consultations',
          description: 'Scheduled 1-on-1 client consultation calls',
          href: '/trainer/consultations',
          iconName: 'consultations',
          status: 'comingSoon',
          badge: { type: 'COMING_SOON', text: 'Coming Soon' },
        },
        {
          id: 'trainer-offers',
          label: 'Offers',
          description: 'Customized client package offers & pricing',
          href: '/trainer/offers',
          iconName: 'offers',
          status: 'comingSoon',
          badge: { type: 'COMING_SOON', text: 'Coming Soon' },
        },
        {
          id: 'trainer-clients',
          label: 'My Clients',
          description: 'Active client roster and coaching management',
          href: '/trainer/clients',
          iconName: 'profile',
          status: 'comingSoon',
          badge: { type: 'COMING_SOON', text: 'Coming Soon' },
        },
      ],
    },
    {
      id: 'programs',
      title: 'PROGRAMS',
      items: [
        {
          id: 'trainer-workouts',
          label: 'Workouts',
          description: 'Workout plans & exercise prescription library',
          href: '/trainer/workouts',
          iconName: 'workouts',
          status: 'comingSoon',
          badge: { type: 'COMING_SOON', text: 'Coming Soon' },
        },
        {
          id: 'trainer-nutrition',
          label: 'Nutrition',
          description: 'Macro targets & custom diet plans',
          href: '/trainer/nutrition',
          iconName: 'nutrition',
          status: 'comingSoon',
          badge: { type: 'COMING_SOON', text: 'Coming Soon' },
        },
        {
          id: 'trainer-progress',
          label: 'Progress',
          description: 'Client analytics, strength & body metrics',
          href: '/trainer/progress',
          iconName: 'progress',
          status: 'comingSoon',
          badge: { type: 'COMING_SOON', text: 'Coming Soon' },
        },
      ],
    },
    {
      id: 'profile-management',
      title: 'PROFILE & MANAGEMENT',
      items: [
        {
          id: 'trainer-profile',
          label: 'My Profile',
          description: 'Manage professional trainer profile & bio',
          href: '/profile/trainer',
          iconName: 'profile',
          status: 'active',
          pageTitle: 'Profile',
          breadcrumb: ['Dashboard', 'Profile'],
        },
        {
          id: 'trainer-certifications',
          label: 'Certifications',
          description: 'Verified fitness credentials & diplomas',
          href: '/profile/trainer/certifications',
          iconName: 'requests',
          status: 'active',
          pageTitle: 'Certifications',
          breadcrumb: ['Dashboard', 'Certifications'],
        },
        {
          id: 'trainer-showcase',
          label: 'Showcase',
          description: 'Transformation portfolio & achievements',
          href: '/profile/trainer/showcase',
          iconName: 'photos',
          status: 'active',
          pageTitle: 'Showcase',
          breadcrumb: ['Dashboard', 'Showcase'],
        },
        {
          id: 'trainer-availability',
          label: 'Availability',
          description: 'Working hours & consultation slots',
          href: '/profile/trainer/availability',
          iconName: 'consultations',
          status: 'active',
          pageTitle: 'Availability',
          breadcrumb: ['Dashboard', 'Availability'],
        },
      ],
    },
    {
      id: 'account',
      title: 'ACCOUNT',
      items: [
        {
          id: 'trainer-settings',
          label: 'Settings',
          description: 'Security, password & account preferences',
          href: '/trainer/settings',
          iconName: 'settings',
          status: 'active',
          pageTitle: 'Settings',
          breadcrumb: ['Dashboard', 'Account', 'Settings'],
        },
        {
          id: 'trainer-help',
          label: 'Help Center',
          description: 'Support guides, FAQ & platform assistance',
          href: '/trainer/help',
          iconName: 'help',
          status: 'comingSoon',
          badge: { type: 'COMING_SOON', text: 'Coming Soon' },
        },
      ],
    },
  ],
};
