export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  UNAUTHORIZED: '/unauthorized',
  CLIENT_DASHBOARD: '/client',
  CLIENT_PROFILE: '/profile/client',
  CLIENT_PROFILE_CREATE: '/profile/client/create',
  CLIENT_PROFILE_EDIT: '/profile/client/edit',
  TRAINER_DASHBOARD: '/trainer',
  TRAINER_PROFILE: '/profile/trainer',
  TRAINER_PROFILE_CREATE: '/profile/trainer/create',
  TRAINER_PROFILE_EDIT: '/profile/trainer/edit',
  TRAINER_AVAILABILITY: '/profile/trainer/availability',
  TRAINER_CERTIFICATIONS: '/profile/trainer/certifications',
  TRAINER_SHOWCASE: '/profile/trainer/showcase',
  PUBLIC_TRAINERS: '/trainers',
  PUBLIC_TRAINER_DETAILS: (id: string) => `/trainers/${id}`,
  CLIENT_CONSULTATIONS: '/client/consultations',
  CLIENT_CONSULTATION_DETAIL: (id: string) => `/client/consultations/${id}`,
  CLIENT_CONSULTATION_ROOM: (id: string) => `/client/consultations/${id}/room`,
  TRAINER_CONSULTATIONS: '/trainer/consultations',
  TRAINER_CONSULTATION_DETAIL: (id: string) => `/trainer/consultations/${id}`,
  TRAINER_CONSULTATION_ROOM: (id: string) => `/trainer/consultations/${id}/room`,
  CLIENT_OFFERS: '/client/offers',
  TRAINER_OFFERS: '/trainer/offers',
} as const;
