import {
  LayoutDashboard,
  Search,
  FileText,
  Calendar,
  Gift,
  Dumbbell,
  Apple,
  TrendingUp,
  Camera,
  Ruler,
  Target,
  MessageSquare,
  Video,
  Bell,
  CreditCard,
  History,
  Receipt,
  User,
  Settings,
  HelpCircle,
  LogOut,
  ChevronLeft,
  ChevronRight,
  Menu,
  X,
  LucideIcon,
} from 'lucide-react';
import { SidebarIconName } from '../types/navigation.types';

const iconMap: Record<SidebarIconName, LucideIcon> = {
  dashboard: LayoutDashboard,
  search: Search,
  requests: FileText,
  consultations: Calendar,
  offers: Gift,
  workouts: Dumbbell,
  nutrition: Apple,
  progress: TrendingUp,
  photos: Camera,
  measurements: Ruler,
  goals: Target,
  messages: MessageSquare,
  video: Video,
  notifications: Bell,
  subscription: CreditCard,
  history: History,
  invoices: Receipt,
  profile: User,
  settings: Settings,
  help: HelpCircle,
  logout: LogOut,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  menu: Menu,
  close: X,
};

export const getSidebarIcon = (iconName: SidebarIconName): LucideIcon => {
  return iconMap[iconName] || LayoutDashboard;
};
